### ISSUE TITLE
Click to Upload

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#12]
Click to upload no longer functions - It doesn't error out but also doesn't allow uploading through the desktop wallet. Drag & drop is still functional (I tried multiple things for click to upload to work). I haven't had any issues with drag & drop directories breaking up as you would see on the web version.

**Comment by Dev-JamesR** [comment]
Click to upload fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/88e95c75c64d9bbcd3351da8188356c6c4c5a377
