### ISSUE TITLE
Modals Error 2

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#17]
```Waiting For Confirmation | ethoFS Block Tracker``` - Does not appear.

```Preparing Data Upload | ethoFS Block Tracker``` - Does not appear.

These are no big problems however it does make it seem like there is an error for the end-user which can be problematic

**Comment by Dev-JamesR** [comment]
Fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/6539344d125579eff921c5e9754fa4b6e7c6ac49
