### ISSUE TITLE
Data Upload completion.

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#18]
After the data upload is completed if you attempt to upload more data immediately then you will be met with the error message: 
```
TypeError: Cannot set property 'innerHTML' of null
    at resetUploadSystem (<anonymous>:443:25)
    at finishUploadModal (<anonymous>:413:5)
    at verifyDataUpload (<anonymous>:356:25)

 Data Confirmation Error: undefined
```

**Comment by fallengravity** [comment]
I just noticed it also continues uploading data 😂 
```
Data Upload Confirmation Received: 115/3
```

**Comment by Dev-JamesR** [comment]
Fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/cbd296ab3558b5990cc7ebd51a2f25f98b1e17b3
