### ISSUE TITLE
Account upload. 

### ISSUE THREAD

**Issue by enkitunes** [Ether1Project/Ether1DesktopWallet#2]
I intentionally uploaded the wrong file. I tried with a .jpg, .pdf and .txt. After the error box closed the wallet froze forcing you to restart it. 

![clipboard01](https://user-images.githubusercontent.com/35766707/50469396-0d3ba080-0961-11e9-9c3b-90e6bd293789.png)

**Comment by fallengravity** [comment]
Resolved.
