### ISSUE TITLE
Duplicated Contract Details Modal.

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#27]
For some odd reason, I'm still getting a duplicated modal on contract details, first one is dismissable, the second is not.

**Comment by Dev-JamesR** [comment]
Fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/34713e4dccaea504e3c7cb781ab1e786ad50ed5c (Tested on Windows)
