### ISSUE TITLE
Upload to ethoFS

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#28]
Upload to ethoFS button no longer functions, no errors in the console.

**Comment by fallengravity** [comment]
Found a start to a possible patch, when you add:

```
var uploadButton = document.getElementById("main-upload-button");
    uploadButton.style.display = "block";
    $('#defaultModal').iziModal();
    $('#defaultModal').iziModal('open');
``` 

to:

```
afterLoginState() {
```

It fires the modal straight away and doesn't let you progress to the next but it does actually open the modal.

**Comment by Dev-JamesR** [comment]
Fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/3045dd050c521be6747fcc3ea69f26f4b97ec441
