### ISSUE TITLE
Deleting the contract via the table

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#29]
If you dismiss the modal which appears it will break the page with a dark overlay - which can be removed by clicking out of the area. After this has happened the page is no longer scrollable and requires a refresh to begin operating again.

**Comment by Dev-JamesR** [comment]
Should be fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/34713e4dccaea504e3c7cb781ab1e786ad50ed5c
