### ISSUE TITLE
Incorrect MB sizing

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#31]
![Screenshot 2019-10-17 at 14 50 00](https://user-images.githubusercontent.com/37632291/67010185-74dbfb80-f0ed-11e9-8827-c9977ecdf751.png)
Seems as though the sizes of directories are not being calculated correctly

**Comment by Dev-JamesR** [comment]
Fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/a8757c55e5db8ccdcc8b19ee1287ce9f498a3710
