### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#35]
If you start an upload and give it files, then leave the tab and then go back and login, when you get to the part where you select files you get:
```
Uncaught TypeError: Cannot set property 'innerText' of undefined uploads.js:1119 
```

**Comment by Dev-JamesR** [comment]
Fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/907791f8c8493eb367705cd3463d74da465646a8
