### ISSUE TITLE
No option to navigate back to wallet 

### ISSUE THREAD

**Issue by Exlo84** [Ether1Project/Ether1DesktopWallet#40]
Cannot navigate back to the wallet after opening links from About Us.

**Comment by Exlo84** [comment]
Edit....
Links in general, not only from About us

**Comment by fallengravity** [comment]
Fixed in https://github.com/Ether1Project/Ether1DesktopWallet/commit/86618060ff63dd1d33133bfc83b7f99c2c58dfeb && https://github.com/Ether1Project/Ether1DesktopWallet/commit/0471c224c40a611710bd6d51dfe1b1925e690c3e
