### ISSUE TITLE
Registering with ethoFS (choosing name)

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/Ether1DesktopWallet#41]
At the step which chooses the name, the text is black along with the background which obfuscates the text.  In the attached screenshot I have already chosen the name and can see it when I select all the text within the black field.

**Comment by Primate411** [comment]
![image](https://user-images.githubusercontent.com/36507842/67292243-c51dd980-f4b0-11e9-9cf0-798a2312c856.png)

**Comment by fallengravity** [comment]
Fixed in https://github.com/Ether1Project/Ether1DesktopWallet/commit/61e15942f42a6d356aea914fc9b9063fef0a9ae2
