### ISSUE TITLE
macOS unable to drop file into selector

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/Ether1DesktopWallet#42]
On macOS I am unable to drop an ethoFS file into the upload box.  Selecting a directory works fine. 

When dropping a file into the box nothing happens.

**Comment by fallengravity** [comment]
Error:
```
/renderer/uploads.js:905 Uncaught TypeError: Cannot read property 'hasChildNodes' of undefined
```

CC: @Dev-JamesR

**Comment by fallengravity** [comment]
```
/renderer/uploads.js:1226 Uncaught TypeError: Cannot read property 'files' of undefined
```

**Comment by Dev-JamesR** [comment]
Should be fixed on https://github.com/Ether1Project/Ether1DesktopWallet/commit/907791f8c8493eb367705cd3463d74da465646a8
