### ISSUE TITLE
Outgoing transactions icon

### ISSUE THREAD

**Issue by dylie** [Ether1Project/Ether1DesktopWallet#43]
Right now the incoming transactions icon on the #Transactions tab is green and pointing inwards (This is good imo) BUT the outgoing transactions show a grey arrow going both ways. It might be good to change this arrow to a red arrow pointing away.

Kind Regards, 

Dylie

**Comment by fallengravity** [comment]
Fixed in https://github.com/Ether1Project/Ether1DesktopWallet/commit/80d5155a12cdfa1d0d89818d39cffc8a6c25cf78
