### ISSUE TITLE
Wallet name change option color scheme

### ISSUE THREAD

**Issue by dylie** [Ether1Project/Ether1DesktopWallet#44]
Hey, the coloring scheme for the name change menu inside the #Wallets tab is not on point yet.

I suggest changing the fully black {WALLET NAME] To White. Also the line that marks the downside of the box where u have to type shows a blue line when hovering. This should be changed to the main ETHO colors.

Kinds regards,

Dylie Da Real G

**Comment by fallengravity** [comment]
Fixed in https://github.com/Ether1Project/Ether1DesktopWallet/commit/03330f37760b72f7220154c97f9d04bfe5e1cead
