### ISSUE TITLE
Add a button in the #wallets tab to remove a wallet

### ISSUE THREAD

**Issue by dylie** [Ether1Project/Ether1DesktopWallet#45]
Suggestion: Add an 'X' Cross button right next to where the wallet balance displays (Same button layout as the qr code, transactions etc box), makes it easy and possible to remove a wallet from your wallet list in case people wan't to remove a wallet from their list.

Kind Regards,

Dylie Dylan

**Comment by newCodeRunner** [comment]
Pushed a PR for this. #65
