### ISSUE TITLE
Hard to read text in "Send"

### ISSUE THREAD

**Issue by Exlo84** [Ether1Project/Ether1DesktopWallet#49]
Hard to read text in "Send" when sending funds
Needs other colours

**Comment by Exlo84** [comment]
![ethobetawallet](https://user-images.githubusercontent.com/46317321/67377249-aa696480-f585-11e9-986c-637073ce5266.jpg)

**Comment by fallengravity** [comment]
Fixed in https://github.com/Ether1Project/Ether1DesktopWallet/commit/2ac19d397d0b2edebb938e5d350e54c09625c1e3
