### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by cryptobytes45** [Ether1Project/Ether1DesktopWallet#5]
All the sudden when I open the app it won't sync, I just get Application error something went wrong, don't kill the fish. Error Connection not open.

**Comment by Primate411** [comment]
Hi @cryptobytes45 you need to close the application and delete the folder contents in `%appdata%\Ether1\geth\chaindata` and then relaunch the application and let the blockchain download again.  Make sure you always have a backup of your keystore files before performing any operation that could delete them.

**Comment by fallengravity** [comment]
Closed due to inactivity.
