### ISSUE TITLE
Password shows up in plain text 

### ISSUE THREAD

**Issue by Exlo84** [Ether1Project/Ether1DesktopWallet#53]
If wallet is chosen when logging in to ethoFS, password shows up in plain text when typing

**Comment by Exlo84** [comment]
<img width="447" alt="wallet password" src="https://user-images.githubusercontent.com/46317321/67619126-0804e780-f7f8-11e9-8ef4-ed9d0e0713a3.png">

**Comment by Exlo84** [comment]
<img width="447" alt="wallet password" src="https://user-images.githubusercontent.com/46317321/67619138-2f5bb480-f7f8-11e9-8ef8-b76a64b5991d.png">

**Comment by fallengravity** [comment]
Addressed in https://github.com/Ether1Project/Ether1DesktopWallet/commit/414fe6c639590581c429c0880190e5afa29e2d79
