### ISSUE TITLE
Send screen white space 

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/Ether1DesktopWallet#56]
When clicking on a wallet using drop down, it should show the wallet address or name and not the white space  

![E48E9C1A-D6B2-462B-904E-364D58C2D37E](https://user-images.githubusercontent.com/36507842/71592737-6784b980-2aff-11ea-837f-906e770cb236.jpeg)

**Comment by Primate411** [comment]
Enhancement report via RedPlumpTomato

**Comment by newCodeRunner** [comment]
Occurs on windows only. Created a PR.
