### ISSUE TITLE
Fix .zip export formatting

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/Ether1DesktopWallet#58]
Can perhaps add a default name containing .zip?

![image](https://user-images.githubusercontent.com/36507842/73104364-43c94f00-3ec4-11ea-8608-2dd233a863a4.png)

**Comment by Primate411** [comment]
Wasn't able to post corresponding issue on Xerom repo, option was missing to add issues

**Comment by newCodeRunner** [comment]
@Primate411 , is this the issue regarding exporting wallets as in the picture below. If so I am unable to reproduce on win 10 Home (Build 19042.508). which windows version is this?


![Capture](https://user-images.githubusercontent.com/57590297/101471938-bf5fad80-3969-11eb-96a5-b2e45850018d.PNG)
