### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by sharmanov1** [Ether1Project/Ether1DesktopWallet#6]
Mostly wallet doesn't connect to peers, and when it does it doesn't load blocks

**Comment by fallengravity** [comment]
Need more information.

OS: 
Architecture:
Wallet Version:

Have you tried bootstraping?

**Comment by sharmanov1** [comment]
Yes, bootstrap seems to have resolved connection issues. I downloaded it a few minutes ago before getting your reply. Thanks anyways.
