### ISSUE TITLE
Saving geth information in differing locations

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/Ether1DesktopWallet#60]
Some users have reported that their geth chain and keystore does not go into the Roadming directory under their user profiles but the Local directory instead.  This change seems to not impact most functions but functions like wallet export rely on the first and crash (shown below)

![image](https://user-images.githubusercontent.com/36507842/73561556-331a5b00-4427-11ea-836a-1d40c7e865f2.png)

**Comment by newCodeRunner** [comment]
Similar to issue  #62 . Fixed in PR #63
