### ISSUE TITLE
(To Be Fixed in Kepler) Cannot Export Wallets

### ISSUE THREAD

**Issue by fallengravity** [Ether1Project/Ether1DesktopWallet#62]
Error:

![image](https://user-images.githubusercontent.com/37632291/94700745-1f1f5400-033c-11eb-9214-5b192562b472.png)

Maybe be related to Updated packages from the last version, needs debugging.

**Comment by newCodeRunner** [comment]
Is this the exports button on wallets page? Works on Mac. you appear to be on windows. is this only a windows problem?
<img width="779" alt="Screenshot 2020-12-08 at 2 51 40 PM" src="https://user-images.githubusercontent.com/57590297/101468450-3cd4ef00-3965-11eb-9753-385f51bc1d6c.png">

**Comment by newCodeRunner** [comment]
Created a pull request to fix this for windows.
