### ISSUE TITLE
How do you generate geth files (geth.exe ...) that are inside /bin folder?

### ISSUE THREAD

**Issue by kevin-wad** [Ether1Project/Ether1DesktopWallet#95]
Hi,

I'm wondering how we are supposed to generate the geth files inside /bin folder?
Can you give quick explanation so I can update for each os (win, linux and macos)?

Thank you very much!

**Comment by kevin-wad** [comment]
I get "spawn UNKNOWN" when I simply copy and paste from core-geth 's build/bingeth file in the wallet /bin folder

**Comment by Exlo84** [comment]
> Hi,
> 
> I'm wondering how we are supposed to generate the geth files inside /bin folder? Can you give quick explanation so I can update for each os (win, linux and macos)?
> 
> Thank you very much!

Geth are imported from main: https://github.com/Ether1Project/Ether1
Either use the precompiled ones, or compile geth from source
